apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: catherineamf/webapp:latest
        ports:
        - containerPort: 80
        env:
        - name: RAILS_ENV
          value: "production"
        readinessProbe:
          httpGet:
            path: "/health" # Обновлено для правильного маршрута
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: "/health" # Добавлена liveness-probe
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 20
        resources: # Рекомендуется добавить лимиты ресурсов
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1"
